import type { DecorDefinition } from './types';

/**
 * Scene-local safety catalog. The richer data catalog can use the same ids and
 * texture keys, allowing these entries to quietly become fallbacks.
 */
export const FALLBACK_DECOR_CATALOG: readonly DecorDefinition[] = [
  {
    id: 'low-desk',
    name: 'Hinoki Study Desk',
    nameJa: 'ひのきの文机',
    description: 'A low cypress desk with a tiny drawer.',
    price: 680,
    footprint: { width: 32, height: 18 },
    locations: ['room'],
    category: 'desk',
  },
  {
    id: 'floor-chair',
    name: 'Floor Chair',
    nameJa: '座椅子',
    price: 320,
    footprint: { width: 18, height: 16 },
    locations: ['room'],
    category: 'seating',
  },
  {
    id: 'kotatsu',
    name: 'Persimmon Kotatsu',
    nameJa: '柿色のこたつ',
    price: 920,
    footprint: { width: 38, height: 28 },
    locations: ['room'],
    category: 'tabletop',
  },
  {
    id: 'bookshelf',
    name: 'Slim Bookcase',
    nameJa: '本棚',
    price: 760,
    footprint: { width: 30, height: 14 },
    locations: ['room'],
    category: 'storage',
  },
  {
    id: 'paper-lamp',
    name: 'Washi Floor Lamp',
    nameJa: '和紙のあかり',
    price: 440,
    footprint: { width: 14, height: 12 },
    locations: ['room', 'garden'],
    category: 'lighting',
  },
  {
    id: 'zabuton',
    name: 'Indigo Zabuton',
    nameJa: '藍色の座布団',
    price: 180,
    footprint: { width: 18, height: 14 },
    locations: ['room'],
    category: 'soft',
  },
  {
    id: 'tea-set',
    name: 'Oribe Tea Set',
    nameJa: '織部の茶器',
    price: 260,
    footprint: { width: 14, height: 10 },
    locations: ['room'],
    category: 'tabletop',
  },
  {
    id: 'monstera',
    name: 'Window Monstera',
    nameJa: '窓辺のモンステラ',
    price: 380,
    footprint: { width: 16, height: 14 },
    locations: ['room', 'cafe'],
    category: 'plants',
  },
  {
    id: 'record-player',
    name: 'Walnut Record Player',
    nameJa: 'くるみのレコード',
    price: 1_100,
    footprint: { width: 24, height: 16 },
    locations: ['room'],
    category: 'tabletop',
  },
  {
    id: 'futon',
    name: 'Cloud Futon',
    nameJa: '雲の布団',
    price: 620,
    footprint: { width: 28, height: 42 },
    locations: ['room'],
    category: 'soft',
  },
  {
    id: 'stone-lantern',
    name: 'Mossy Stone Lantern',
    nameJa: '苔の石灯籠',
    price: 740,
    footprint: { width: 20, height: 18 },
    locations: ['garden'],
    category: 'garden',
  },
  {
    id: 'hydrangea',
    name: 'Rain Hydrangea',
    nameJa: '雨色のあじさい',
    price: 360,
    footprint: { width: 24, height: 18 },
    locations: ['garden'],
    category: 'garden',
  },
  {
    id: 'maple-sapling',
    name: 'Little Maple',
    nameJa: 'もみじの若木',
    price: 520,
    footprint: { width: 24, height: 20 },
    locations: ['garden'],
    category: 'garden',
  },
  {
    id: 'wind-chime',
    name: 'Blue Fūrin',
    nameJa: '青い風鈴',
    price: 280,
    footprint: { width: 12, height: 10 },
    locations: ['garden', 'room'],
    category: 'garden',
  },
] as const;

export function fallbackDecorById(id: string): DecorDefinition | undefined {
  return FALLBACK_DECOR_CATALOG.find((item) => item.id === id);
}
