import type { LocationBlueprint, LocationId } from './types';

const ROOM: LocationBlueprint = {
  id: 'room',
  name: 'Komorebi House',
  nameJa: '木漏れ日の家',
  subtitle: 'A small room, made entirely yours',
  bounds: { x: 0, y: 0, width: 480, height: 270 },
  surface: 'tatami',
  skyColor: 0x9dc3af,
  groundColor: 0xd8c78e,
  groundAccent: 0xb7a872,
  defaultSpawn: 'center',
  spawns: {
    center: { x: 240, y: 172 },
    fromGarden: { x: 240, y: 224 },
    fromCafe: { x: 104, y: 214 },
  },
  placementAreas: [{ x: 58, y: 104, width: 364, height: 124 }],
  obstacles: [
    { x: 38, y: 0, width: 404, height: 96 },
    { x: 0, y: 0, width: 48, height: 250 },
    { x: 432, y: 0, width: 48, height: 250 },
    { x: 0, y: 248, width: 66, height: 22 },
    { x: 124, y: 248, width: 78, height: 22 },
    { x: 278, y: 248, width: 132, height: 22 },
    { x: 468, y: 248, width: 12, height: 22 },
  ],
  portals: [
    {
      id: 'room-garden',
      x: 206,
      y: 232,
      width: 70,
      height: 38,
      destination: 'garden',
      destinationSpawn: 'fromRoom',
      label: 'Step out to the garden',
    },
    {
      id: 'room-cafe',
      x: 66,
      y: 224,
      width: 58,
      height: 46,
      destination: 'cafe',
      destinationSpawn: 'fromRoom',
      label: 'Walk to Kissa Komorebi Café',
    },
  ],
  interactions: [
    {
      id: 'room-study',
      x: 136,
      y: 112,
      label: 'Settle in for a study session',
      labelJa: '勉強をはじめる',
      kind: 'study',
    },
    {
      id: 'room-window',
      x: 300,
      y: 102,
      label: 'Watch the light move through the leaves',
      labelJa: '木漏れ日を眺める',
      kind: 'observe',
      message: 'A patch of sunlight drifts quietly across the tatami.',
    },
    {
      id: 'room-shelf',
      x: 118,
      y: 82,
      label: 'Choose a book',
      labelJa: '本を読む',
      kind: 'read',
      message: 'You find a slim book of seasonal poems.',
    },
    {
      id: 'room-tokonoma',
      x: 380,
      y: 108,
      label: 'Refresh the seasonal flowers',
      labelJa: '季節の花を飾る',
      kind: 'observe',
      message: 'One bright branch is enough to change the whole room.',
    },
  ],
  ambience: 'dust',
};

const GARDEN: LocationBlueprint = {
  id: 'garden',
  name: 'Moonfern Garden',
  nameJa: '月しだの庭',
  subtitle: 'Moss, rainwater and one perfect maple',
  bounds: { x: 0, y: 0, width: 480, height: 270 },
  surface: 'grass',
  skyColor: 0x91bca8,
  groundColor: 0x7ea06b,
  groundAccent: 0x66865b,
  defaultSpawn: 'fromRoom',
  spawns: {
    fromRoom: { x: 240, y: 112 },
    fromPark: { x: 240, y: 214 },
  },
  placementAreas: [
    { x: 132, y: 110, width: 112, height: 92 },
    { x: 58, y: 168, width: 126, height: 66 },
    { x: 366, y: 166, width: 70, height: 64 },
  ],
  obstacles: [
    { x: 26, y: 0, width: 428, height: 68 },
    { x: 0, y: 0, width: 28, height: 252 },
    { x: 452, y: 0, width: 28, height: 252 },
    { x: 0, y: 62, width: 126, height: 108 },
    { x: 258, y: 68, width: 132, height: 100 },
    { x: 0, y: 252, width: 208, height: 18 },
    { x: 272, y: 252, width: 208, height: 18 },
  ],
  portals: [
    {
      id: 'garden-room',
      x: 190,
      y: 52,
      width: 98,
      height: 46,
      destination: 'room',
      destinationSpawn: 'fromGarden',
      label: 'Go inside',
    },
    {
      id: 'garden-park',
      x: 208,
      y: 232,
      width: 64,
      height: 38,
      destination: 'park',
      destinationSpawn: 'fromGarden',
      label: 'Follow the lane to the park',
    },
  ],
  interactions: [
    {
      id: 'garden-bench',
      x: 126,
      y: 208,
      label: 'Study beneath the maple',
      labelJa: 'もみじの下で勉強する',
      kind: 'study',
    },
    {
      id: 'garden-pond',
      x: 96,
      y: 138,
      label: 'Watch the medaka',
      labelJa: 'メダカを眺める',
      kind: 'observe',
      message: 'Tiny silver fish make commas in the dark water.',
    },
    {
      id: 'garden-basin',
      x: 330,
      y: 144,
      label: 'Water the garden',
      labelJa: '庭に水をやる',
      kind: 'water',
      message: 'The moss deepens to a cool, rain-wet green.',
    },
    {
      id: 'garden-chime',
      x: 114,
      y: 74,
      label: 'Listen to the wind chime',
      labelJa: '風鈴の音を聴く',
      kind: 'listen',
      message: 'A single glass note disappears into the afternoon.',
    },
  ],
  ambience: 'petals',
};

const CAFE: LocationBlueprint = {
  id: 'cafe',
  name: 'Kissa Komorebi Café',
  nameJa: '喫茶こもれび',
  subtitle: 'Coffee, old jazz and a window seat',
  bounds: { x: 0, y: 0, width: 480, height: 270 },
  surface: 'wood',
  skyColor: 0x754f49,
  groundColor: 0x9a694e,
  groundAccent: 0x744b3b,
  defaultSpawn: 'fromRoom',
  spawns: {
    fromRoom: { x: 222, y: 232 },
    fromPark: { x: 258, y: 232 },
  },
  placementAreas: [],
  obstacles: [
    { x: 20, y: 0, width: 440, height: 42 },
    { x: 0, y: 0, width: 24, height: 252 },
    { x: 456, y: 0, width: 24, height: 252 },
    { x: 24, y: 58, width: 108, height: 84 },
    { x: 258, y: 42, width: 198, height: 92 },
    { x: 144, y: 138, width: 96, height: 68 },
    { x: 354, y: 120, width: 96, height: 72 },
    { x: 0, y: 188, width: 144, height: 58 },
    { x: 0, y: 252, width: 196, height: 18 },
    { x: 284, y: 252, width: 196, height: 18 },
  ],
  portals: [
    {
      id: 'cafe-room',
      x: 196,
      y: 234,
      width: 44,
      height: 36,
      destination: 'room',
      destinationSpawn: 'fromCafe',
      label: 'Walk home',
    },
    {
      id: 'cafe-park',
      x: 240,
      y: 234,
      width: 44,
      height: 36,
      destination: 'park',
      destinationSpawn: 'fromCafe',
      label: 'Walk to Hoshimi Park',
    },
  ],
  interactions: [
    {
      id: 'cafe-counter',
      x: 302,
      y: 138,
      label: 'Browse today’s small treasures',
      labelJa: '今日の品を見る',
      kind: 'shop',
    },
    {
      id: 'cafe-window-study',
      x: 134,
      y: 128,
      label: 'Study at the window table',
      labelJa: '窓辺で勉強する',
      kind: 'study',
    },
    {
      id: 'cafe-coffee',
      x: 190,
      y: 180,
      label: 'Enjoy a hand-drip coffee',
      labelJa: '珈琲を味わう',
      kind: 'drink',
      message: 'The cup is warm in both hands. Chocolate, cedar, and a little citrus.',
    },
    {
      id: 'cafe-jukebox',
      x: 332,
      y: 108,
      label: 'Choose an old jazz record',
      labelJa: 'ジャズを選ぶ',
      kind: 'listen',
      message: 'A brushed snare begins somewhere behind the coffee steam.',
    },
  ],
  ambience: 'steam',
};

const PARK: LocationBlueprint = {
  id: 'park',
  name: 'Hoshimi Park',
  nameJa: '星見公園',
  subtitle: 'A quiet neighborhood park above the river',
  bounds: { x: 0, y: 0, width: 480, height: 270 },
  surface: 'stone',
  skyColor: 0x87afab,
  groundColor: 0x78996b,
  groundAccent: 0x607f5b,
  defaultSpawn: 'fromCafe',
  spawns: {
    fromCafe: { x: 394, y: 196 },
    fromGarden: { x: 240, y: 214 },
  },
  placementAreas: [],
  obstacles: [
    { x: 0, y: 0, width: 184, height: 106 },
    { x: 184, y: 0, width: 114, height: 54 },
    { x: 298, y: 0, width: 182, height: 38 },
    { x: 0, y: 106, width: 46, height: 146 },
    { x: 302, y: 44, width: 138, height: 96 },
    { x: 382, y: 96, width: 82, height: 76 },
    { x: 130, y: 106, width: 54, height: 42 },
    { x: 0, y: 252, width: 208, height: 18 },
    { x: 272, y: 252, width: 104, height: 18 },
    { x: 446, y: 226, width: 34, height: 44 },
  ],
  portals: [
    {
      id: 'park-cafe',
      x: 376,
      y: 214,
      width: 70,
      height: 56,
      destination: 'cafe',
      destinationSpawn: 'fromPark',
      label: 'Return to the kissaten',
    },
    {
      id: 'park-garden',
      x: 208,
      y: 232,
      width: 64,
      height: 38,
      destination: 'garden',
      destinationSpawn: 'fromPark',
      label: 'Take the lane home',
    },
  ],
  interactions: [
    {
      id: 'park-river-bench',
      x: 348,
      y: 136,
      label: 'Study beside the river',
      labelJa: '川辺で勉強する',
      kind: 'study',
    },
    {
      id: 'park-river',
      x: 220,
      y: 92,
      label: 'Watch sunlight cross the river',
      labelJa: '川面の光を眺める',
      kind: 'observe',
      message: 'Bright pieces of sky travel downstream between the bridge shadows.',
    },
    {
      id: 'park-picnic',
      x: 142,
      y: 202,
      label: 'Read in the soft grass',
      labelJa: '芝生で本を読む',
      kind: 'read',
      message: 'The page smells faintly of grass and sun-warmed paper.',
    },
    {
      id: 'park-radio',
      x: 402,
      y: 154,
      label: 'Choose a warm canned coffee',
      labelJa: '温かい缶珈琲を選ぶ',
      kind: 'drink',
      message: 'The can warms your hands while the river keeps moving.',
    },
  ],
  ambience: 'fireflies',
};

export const LOCATION_BLUEPRINTS: Readonly<Record<LocationId, LocationBlueprint>> = {
  room: ROOM,
  garden: GARDEN,
  cafe: CAFE,
  park: PARK,
};

export function getLocationBlueprint(id: LocationId): LocationBlueprint {
  return LOCATION_BLUEPRINTS[id];
}
